apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: aaronkolins
data:
  .env: |
    PORT=4040
    PGHOST=postgres-service
    PGUSER=count
    PGDATABASE=count
    PGPORT=5432
    PGPASSWORD=count
    RABBITMQ_URL=amqp://rabbitmq-cluster:5672
    QUEUE=count
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: aaronkolins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: aaronkolins77/backend:latest
        ports:
        - containerPort: 4040
        envFrom:
        - configMapRef:
            name: backend-config
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: aaronkolins
spec:
  type: LoadBalancer
  ports:
  - port: 4040
    targetPort: 4040
  selector:
    app: backend
