apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: aaronkolins
data:
  .env: |
    PORT=4040
    PGHOST=postgres-service
    PGUSER=count
    PGDATABASE=count
    PGPORT=5432
    PGPASSWORD=count
    RABBITMQ_URL=amqp://rabbitmq.aaronkolins.svc.cluster.local:5672
    QUEUE=count
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: aaronkolins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: aaronkolins77/backend:v1
          env:
            - name: RABBITMQ_URL
              value: "amqp://rabbitmq.aaronkolins.svc.cluster.local:5672"
            - name: PGHOST
              value: "backend-service"
            - name: PGPORT
              value: "5432"      
            - name: PGUSER
              value: "myuser"
            # - name: PGDATABASE
            #   value: "mydatabase"
            # - name: PGPASSWORD
            #   value: "mypassword"        
            - name: PORT
              value: "5432"                        
          ports:
            - containerPort: 4040