apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: aaronkolins
  labels:
    app: aaronkolins-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: aaronkolins77/postgres:v1
          ports:
            - containerPort: 5432
          env:
            - name: PORT
              value: '5432'
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: aaronkolins
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: LoadBalancer